#include "MultibandCompressorEffect.h"
#include "au3-math/Biquad.h"
#include <algorithm>
#include <cmath>

namespace au::effects {
const ComponentInterfaceSymbol MultibandCompressorEffect::Symbol{
    XO("Multiband Compressor")
};

MultibandCompressorEffect::MultibandCompressorEffect()
{
}

MultibandCompressorEffect::~MultibandCompressorEffect()
{
}

ComponentInterfaceSymbol MultibandCompressorEffect::GetSymbol() const
{
    return Symbol;
}

::EffectType MultibandCompressorEffect::GetType() const
{
    return EffectTypeProcess;
}

OptionalMessage MultibandCompressorEffect::LoadFactoryDefaults(EffectSettings& settings) const
{
    GetSettings(settings) = MultibandCompressorSettings{};
    return {};
}

unsigned MultibandCompressorEffect::GetAudioInCount() const
{
    return 1;
}

unsigned MultibandCompressorEffect::GetAudioOutCount() const
{
    return 1;
}

bool MultibandCompressorEffect::Init()
{
    return true;
}

MultibandCompressorEffect::Instance::Instance(const PerTrackEffect& effect)
    : StatefulPerTrackEffect::Instance(effect)
{
}

MultibandCompressorEffect::Instance::~Instance()
{
}

bool MultibandCompressorEffect::Instance::ProcessInitialize(
    EffectSettings& settings, double sampleRate, ChannelNames chanMap)
{
    mSampleRate = sampleRate;
    mChannels = chanMap.size();

    for (int i = 0; i < 3; ++i) {
        mCompressors[i].clear();
        for (size_t c = 0; c < mChannels; ++c) {
            mCompressors[i].push_back(std::make_unique<CompressorProcessor>());
        }
    }

    mLowPass1.resize(mChannels);
    mHighPass1.resize(mChannels);
    mLowPass2.resize(mChannels);
    mHighPass2.resize(mChannels);

    // Initialize buffers later when block size is known (if needed, but EffectInstanceWithBlockSize provides GetBlockSize())
    return true;
}

size_t MultibandCompressorEffect::Instance::ProcessBlock(EffectSettings& settings, const float* const* inBlock, float* const* outBlock,
                                                         size_t blockLen)
{
    const auto& s = GetSettings(settings);

    if (mLowBuffer.size() < blockLen * mChannels) {
        mLowBuffer.resize(blockLen * mChannels);
        mMidBuffer.resize(blockLen * mChannels);
        mHighBuffer.resize(blockLen * mChannels);
        mLowPtrs.resize(mChannels);
        mMidPtrs.resize(mChannels);
        mHighPtrs.resize(mChannels);
        for (size_t c = 0; c < mChannels; ++c) {
            mLowPtrs[c] = mLowBuffer.data() + c * blockLen;
            mMidPtrs[c] = mMidBuffer.data() + c * blockLen;
            mHighPtrs[c] = mHighBuffer.data() + c * blockLen;
        }
    }

    // Simple Linkwitz-Riley or Butterworth crossover would be applied here
    // For now we just use the Biquad filters generated by CalcButterworthFilter
    // Biquad requires freq normalized by Nyquist
    double nyquist = mSampleRate / 2.0;
    double normFreq1 = std::clamp(s.crossover1Freq / nyquist, 0.01, 0.99);
    double normFreq2 = std::clamp(s.crossover2Freq / nyquist, 0.01, 0.99);

    auto lp1_arr = Biquad::CalcButterworthFilter(2, normFreq1, s.crossover1Freq, Biquad::kLowPass);
    auto hp1_arr = Biquad::CalcButterworthFilter(2, normFreq1, s.crossover1Freq, Biquad::kHighPass);
    auto lp2_arr = Biquad::CalcButterworthFilter(2, normFreq2, s.crossover2Freq, Biquad::kLowPass);
    auto hp2_arr = Biquad::CalcButterworthFilter(2, normFreq2, s.crossover2Freq, Biquad::kHighPass);

    for (size_t c = 0; c < mChannels; ++c) {
        // Copy coefficients
        if (lp1_arr.size() > 0) {
            mLowPass1[c] = lp1_arr[0];
        }
        if (hp1_arr.size() > 0) {
            mHighPass1[c] = hp1_arr[0];
        }
        if (lp2_arr.size() > 0) {
            mLowPass2[c] = lp2_arr[0];
        }
        if (hp2_arr.size() > 0) {
            mHighPass2[c] = hp2_arr[0];
        }

        for (size_t i = 0; i < blockLen; ++i) {
            float inSample = inBlock[c] ? inBlock[c][i] : 0.0f;

            // Crossover logic (Linkwitz-Riley structure, approximated with Butterworth)
            float low = mLowPass1[c].ProcessOne(inSample);
            float high1 = mHighPass1[c].ProcessOne(inSample);

            float mid = mLowPass2[c].ProcessOne(high1);
            float high = mHighPass2[c].ProcessOne(high1);

            mLowPtrs[c][i] = low;
            mMidPtrs[c][i] = mid;
            mHighPtrs[c][i] = high;
        }

        // Setup compressor settings
        mCompressors[0][c]->ApplySettingsIfNeeded(DynamicRangeProcessorSettings(s.lowBand));
        mCompressors[0][c]->Init(mSampleRate, 1, blockLen);

        mCompressors[1][c]->ApplySettingsIfNeeded(DynamicRangeProcessorSettings(s.midBand));
        mCompressors[1][c]->Init(mSampleRate, 1, blockLen);

        mCompressors[2][c]->ApplySettingsIfNeeded(DynamicRangeProcessorSettings(s.highBand));
        mCompressors[2][c]->Init(mSampleRate, 1, blockLen);

        // Process each band
        const float* lp_in[1] = { mLowPtrs[c] };
        float* lp_out[1] = { mLowPtrs[c] };
        mCompressors[0][c]->Process(lp_in, lp_out, blockLen);

        const float* mp_in[1] = { mMidPtrs[c] };
        float* mp_out[1] = { mMidPtrs[c] };
        mCompressors[1][c]->Process(mp_in, mp_out, blockLen);

        const float* hp_in[1] = { mHighPtrs[c] };
        float* hp_out[1] = { mHighPtrs[c] };
        mCompressors[2][c]->Process(hp_in, hp_out, blockLen);

        // Mixdown
        if (outBlock[c]) {
            float makeupLinear = std::pow(10.0f, s.makeUpGain / 20.0f);
            for (size_t i = 0; i < blockLen; ++i) {
                outBlock[c][i] = (mLowPtrs[c][i] + mMidPtrs[c][i] + mHighPtrs[c][i]) * makeupLinear;
            }
        }
    }

    return blockLen;
}

bool MultibandCompressorEffect::Instance::ProcessFinalize() noexcept
{
    return true;
}
}
